version: '3.2'

services:
  elasticsearch:
    image: eu.gcr.io/trustseu/anonymisation_de-anonymisation_risk_analysis_elasticsearch    
    volumes:
      - type: bind
        source: ./elk/elasticsearch/config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: bind
        source: ./elk/elasticsearch/data
        target: /usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx1g -Xms1g"
      ELASTIC_PASSWORD: changeme
      discovery.type: single-node  
    networks:
      - elk

  logstash:
    image: eu.gcr.io/trustseu/anonymisation_de-anonymisation_risk_analysis_logstash
    volumes:
      - type: bind
        source: ./elk/logstash/config/logstash.yml
        target: /usr/share/logstash/config/logstash.yml
        read_only: true
      - type: bind
        source: ./elk/logstash/pipeline
        target: /usr/share/logstash/pipeline
        read_only: true
      - ./elk/logstash/user_datasets:/usr/share/logstash/user_datasets #
    ports:
      - "5044:5044"
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "9600:9600"
      - "8084:8084" #
    environment:
      LS_JAVA_OPTS: "-Xmx1g -Xms1g"
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    image: eu.gcr.io/trustseu/anonymisation_de-anonymisation_risk_analysis_kibana
    volumes:
      - type: bind
        source: ./elk/kibana/config/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

  frontend:    
    image: eu.gcr.io/trustseu/anonymisation_de-anonymisation_risk_analysis_trusts_visual_analytics
    ports:
      - "80:80"  
    networks:
      - elk

  datatransfer_server:    
    image: eu.gcr.io/trustseu/anonymisation_de-anonymisation_risk_analysis_trusts_datatransfer_server
    ports:
      - "4560:4560"  
    volumes:
        - ./user_datasets:/usr/src/app/user_datasets
    links:
      - elasticsearch
    networks:
      - elk
  
  privacy_backend:
    image: eu.gcr.io/trustseu/anonymisation_de-anonymisation_risk_analysis_privacy_backend
    ports:
      - "4201:4201"  
    volumes:
      - ./user_datasets:/user_datasets
    links:
      - elasticsearch
    networks:
      - elk
networks:
  elk:
    driver: bridge


