package app;

import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;

@RestController
public class LDiversityResponse {

    @GetMapping("/ldiversitytest")
    public String test() {
        return "{\n"
                + "  \"took\" : 0,\n"
                + "  \"timed_out\" : false,\n"
                + "  \"_shards\" : {\n"
                + "    \"total\" : 1,\n"
                + "    \"successful\" : 1,\n"
                + "    \"skipped\" : 0,\n"
                + "    \"failed\" : 0\n"
                + "  },\n"
                + "  \"hits\" : {\n"
                + "    \"total\" : {\n"
                + "      \"value\" : 2,\n"
                + "      \"relation\" : \"eq\"\n"
                + "    },\n"
                + "    \"max_score\" : 1.0,\n"
                + "    \"hits\" : [\n"
                + "      {\n"
                + "        \"_index\" : \"mr7lrhgbbvv9mujkoqxo_results\",\n"
                + "        \"_type\" : \"_doc\",\n"
                + "        \"_id\" : \"0L7lrHgBBvv9mUjkWwVJ\",\n"
                + "        \"_score\" : 1.0,\n"
                + "        \"_source\" : {\n"
                + "          \"salary-class\" : [\n"
                + "            {\n"
                + "              \"QIs\" : \"1\",\n"
                + "              \"risk\" : \"0.05\",\n"
                + "              \"combination\" : \"workclass\"\n"
                + "            },\n"
                + "            {\n"
                + "              \"QIs\" : \"2\",\n"
                + "              \"risk\" : \"0.05\",\n"
                + "              \"combination\" : \"workclass;sex\"\n"
                + "            },\n"
                + "            {\n"
                + "              \"QIs\" : \"1\",\n"
                + "              \"risk\" : \"0.0\",\n"
                + "              \"combination\" : \"sex\"\n"
                + "            }\n"
                + "          ]\n"
                + "        }\n"
                + "      },\n"
                + "      {\n"
                + "        \"_index\" : \"mr7lrhgbbvv9mujkoqxo_results\",\n"
                + "        \"_type\" : \"_doc\",\n"
                + "        \"_id\" : \"0b7lrHgBBvv9mUjkXAUV\",\n"
                + "        \"_score\" : 1.0,\n"
                + "        \"_source\" : {\n"
                + "          \"race\" : [\n"
                + "            {\n"
                + "              \"QIs\" : \"1\",\n"
                + "              \"risk\" : \"0.0\",\n"
                + "              \"combination\" : \"workclass\"\n"
                + "            },\n"
                + "            {\n"
                + "              \"QIs\" : \"2\",\n"
                + "              \"risk\" : \"0.02\",\n"
                + "              \"combination\" : \"workclass;sex\"\n"
                + "            },\n"
                + "            {\n"
                + "              \"QIs\" : \"1\",\n"
                + "              \"risk\" : \"0.0\",\n"
                + "              \"combination\" : \"sex\"\n"
                + "            }\n"
                + "          ]\n"
                + "        }\n"
                + "      }\n"
                + "    ]\n"
                + "  }\n"
                + "}";
    }
}
